// images
import blogImg1 from "/public/images/blog/primaria-cluj-napoca-calin-cozma-aur.webp";
import blogImg2 from "/public/images/blog/transparenta-si-onestitate-viziunea-lui-Calin-Cozma-pentru-administratia-locala-din-cluj-napoca.webp";
import blogImg3 from "/public/images/blog/Calin-Cozma-Sustinerea-mediului-antreprenorial-prin-festivaluri-si-expozitii.webp";
import blogImg4 from "/public/images/blog/Calin-Cozma-Reactii-la-rezultatele-sondajului-pentru-Primaria-Clujului.webp";
import blogImg5 from "/public/images/blog/george-simion-calin-cozma-combaterea-minciunii-si-amagirii-in-administratia-locala.webp";
import blogImg6 from "/public/images/blog/Calin-Cozma-O-Noua-Viziune-pentru-Cluj-Napoca.webp";
import blogImg7 from "/public/images/blog/Calin-Cozma-Reducerea-Numarului-de-Angajati-din-Primaria-Cluj-Napoca.webp";
import blogImg8 from "/public/images/blog/Calin-Cozma-Opinii-ale-unui-Influencer-Politic-Ardelean.webp";
import blogImg9 from "/public/images/blog/Calin-Cozma-Amintiri-din-Timpul-Revolutiei.webp";
import blogImg10 from "/public/images/blog/Calin-Cozma-Critici-la-Adresa-Administratiei-Boc-pentru-Intarzierile-in-Emiterea-Autorizatiilor-de-Constructie.webp";
import blogImg11 from "/public/images/blog/Calin-Cozma-Propuneri-pentru-Modernizarea-Administratiei-in-Cluj-Napoca.webp";
import blogImg12 from "/public/images/blog/Calin-Cozma-AUR-Denunta-Actiuni-de-Intimidare-si-Vandalizare-in-Campania-din-Cluj.webp";




const blogs = [
    {
        id: '1',
        title: 'Călin Cozma: Candidatura la Primăria Clujului',
        slug:'Calin-Cozma-Candidatura-la-Primaria-Clujului',
        screens: blogImg1,
        description: 'Descoperă motivele pentru care Călin Cozma și-a anunțat candidatura la Primăria Clujului în alegerile din 2024 și viziunea sa pentru oraș.',
        text: 'Călin Cozma este candidatul care își propune să aducă schimbarea în Cluj-Napoca. Artist liric de renume și antreprenor cu experiență, Călin Cozma și-a asumat această candidatură pentru a contribui la dezvoltarea orașului nostru. În articolul de mai jos, vei afla mai multe despre motivele care l-au determinat pe Călin Cozma să intre în cursa pentru Primăria Clujului și despre viziunea sa pentru viitorul orașului.',
        quote:'Sunt singurul dintre candidații înscriși în competiție născut în Cluj-Napoca. Un clujean, român și patriot care își dorește să dezvolte confortul și bunăstarea fiecărui cetățean al acestei urbe! Nu mă lupt pentru o funcție, mă lupt pentru viitorul familiei mele, pentru viitorul Clujului!',
        text2: 'Candidatul pentru Consiliul Local își asumă un angajament hotărât: să formeze o majoritate solidă alături de colegii săi consilieri și să ofere Clujului un nou primar. Este timpul ca orașul să beneficieze de un nou început, iar acesta pare să fie sentimentul general. O nouă conducere poate aduce schimbarea necesară și așteptată de comunitate. Învierea spiritului civic și a responsabilității este esențială pentru viitorul orașului. Se pare că acesta este momentul potrivit pentru o transformare. Cu o experiență variată, de la domeniul artistic la cel antreprenorial, candidatul aduce în competiție o perspectivă proaspătă și o viziune clară asupra direcției în care ar trebui să se îndrepte Cluj-Napoca. Este evident că orașul are nevoie de o schimbare și este datoria noastră să ne asigurăm că viitorul său este mai luminos.',
        sourceLink: 'https://cluj24.ro/aur-si-a-desemnat-candidatul-la-primaria-cluj-calin-cozma-sunt-singurul-dintre-candidatii-inscrisi-nascut-in-cluj-napoca-205650.html',
        source: 'Cluj24.ro',
        author: 'Echipa Călin Cozma',
        create_at: '3 Mai 2024',
    },
    {
        id: '2',
        title: 'Transparență și Onestitate: Viziunea lui Călin Cozma pentru Administrația Locală din Cluj-Napoca',
        slug:'transparenta-si-onestitate-viziunea-lui-Calin-Cozma-pentru-administratia-locala-din-cluj-napoca',
        screens: blogImg2,
        description: 'Călin Cozma subliniază importanța transparenței și onestității în administrația locală și îndeamnă clujenii să nu mai fie amăgiți și mințiți de către administrație.',
        text: 'Călin Cozma este un adept fervent al transparenței și onestității în administrația locală. Într-un interviu recent, el a subliniat importanța comunicării deschise și corecte între autorități și cetățeni. Îndeamnă clujenii să fie vigilenți și să ceară explicații clare și detaliate cu privire la deciziile și acțiunile administrației. Este timpul ca locuitorii Clujului să aibă acces la informații corecte și complete despre modul în care este condus orașul lor.',
        quote:'„Urbea are nevoie de  festivaluri, târguri şi expoziţii  de care să beneficieze tot mediul antreprenorial, nu doar firmele din ţarcul UNTOLD”',
        text2: 'Candidatul pentru Consiliul Local își asumă un angajament hotărât: să formeze o majoritate solidă alături de colegii săi consilieri și să ofere Clujului un nou primar. Este timpul ca orașul să beneficieze de un nou început, iar acesta pare să fie sentimentul general. O nouă conducere poate aduce schimbarea necesară și așteptată de comunitate. Învierea spiritului civic și a responsabilității este esențială pentru viitorul orașului. Se pare că acesta este momentul potrivit pentru o transformare. Cu o experiență variată, de la domeniul artistic la cel antreprenorial, candidatul aduce în competiție o perspectivă proaspătă și o viziune clară asupra direcției în care ar trebui să se îndrepte Cluj-Napoca. Este evident că orașul are nevoie de o schimbare și este datoria noastră să ne asigurăm că viitorul său este mai luminos.',
        sourceLink: 'https://www.presalocala.com/2024/05/09/calin-cozma-clujenii-nu-trebuie-sa-mai-fie-amagiti-si-mintiti-de-catre-administratie/',
        source: 'presalocala.com',
        author: 'Echipa Călin Cozma',
        create_at: '5 Mai 2024',
    },
    {
        id: '3',
        title: 'Călin Cozma: Susținerea mediului antreprenorial prin festivaluri și expoziții',
        slug:'Calin-Cozma-Sustinerea-mediului-antreprenorial-prin-festivaluri-si-expozitii',
        screens: blogImg3,
        description: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, pune accentul pe susținerea mediului antreprenorial local și critică administrația condusă de Emil Boc pentru tratamentul discriminatoriu și birocrația excesivă. ',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a adus în atenția publicului un mesaj ferm cu privire la administrația locală condusă de Emil Boc. El subliniază necesitatea ca întregul mediu antreprenorial din Cluj să beneficieze de evenimente precum festivaluri, târguri și expoziții, nu doar câteva firme privilegiate. Cozma evidențiază dificultățile cu care se confruntă micii întreprinzători, precum chiriile exorbitante, birocrația excesivă și preferințele acordate anumitor operatori economici. Propunerile sale includ simplificarea procedurilor administrative și promovarea unei relații civilizate între administrație și antreprenori, în conformitate cu legea.',
        quote:'Urbea are nevoie de  festivaluri, târguri şi expoziţii  de care să beneficieze tot mediul antreprenorial, nu doar firmele din ţarcul UNTOLD',
        text2: 'În continuare, candidatul AUR la Primăria Cluj-Napoca, Călin Cozma, subliniază că prioritățile sale se axează pe sprijinirea tuturor afacerilor locale și crearea unui mediu propice dezvoltării acestora. El propune soluții rapide și eficiente pentru problemele întâmpinate de antreprenori, iar angajamentul său pentru o administrație transparentă și echitabilă este clar evidențiat. Cozma promite să acorde atenție tuturor sectoarelor economice și să lupte pentru ca niciun business să nu fie tratat discriminatoriu, pledând pentru o abordare justă și deschisă în toate relațiile cu mediul antreprenorial din Cluj-Napoca.',
        sourceLink: 'https://gazetadecluj.ro/calin-cozma-urbea-are-nevoie-de-festivaluri-targuri-si-expozitii-de-care-sa-beneficieze-tot-mediul-antreprenorial-nu-doar-firmele-din-tarcul-untold/',
        source: 'gazetadecluj.ro',
        author: 'Echipa Călin Cozma',
        create_at: '7 Mai 2024',
    },
    {
        id: '4',
        title: 'Călin Cozma: Reacții la rezultatele sondajului pentru Primăria Clujului',
        slug:'Calin-Cozma-Reactii-la-rezultatele-sondajului-pentru-Primaria-Clujului',
        screens: blogImg4,
        description: 'Călin Cozma subliniază rolul crucial al organizării festivalurilor, târgurilor și expozițiilor în susținerea și dezvoltarea mediului antreprenorial din Cluj-Napoca. Prin aceste evenimente, el își propune să ofere oportunități semnificative de promovare și dezvoltare pentru afacerile locale.',
        text: 'În urma publicării rezultatelor unui sondaj de opinie privind alegerile pentru Primăria Clujului, Călin Cozma a exprimat satisfacția sa față de sprijinul și încrederea acordate de către cetățeni. El consideră că rezultatele sondajului reflectă dorința clujenilor de a vedea o schimbare în conducerea orașului și își exprimă hotărârea de a le oferi un nou primar și o nouă viziune pentru viitorul Clujului.',
        quote:'Clujenii nu trebuie să mai fie amăgiți și mințiți de către administrație!',
        text2: 'Candidatul pentru Consiliul Local își asumă un angajament hotărât: să formeze o majoritate solidă alături de colegii săi consilieri și să ofere Clujului un nou primar. Este timpul ca orașul să beneficieze de un nou început, iar acesta pare să fie sentimentul general. O nouă conducere poate aduce schimbarea necesară și așteptată de comunitate. Învierea spiritului civic și a responsabilității este esențială pentru viitorul orașului. Se pare că acesta este momentul potrivit pentru o transformare. Cu o experiență variată, de la domeniul artistic la cel antreprenorial, candidatul aduce în competiție o perspectivă proaspătă și o viziune clară asupra direcției în care ar trebui să se îndrepte Cluj-Napoca. Este evident că orașul are nevoie de o schimbare și este datoria noastră să ne asigurăm că viitorul său este mai luminos.',
        sourceLink: 'https://www.presalocala.com/2024/05/09/calin-cozma-clujenii-nu-trebuie-sa-mai-fie-amagiti-si-mintiti-de-catre-administratie/',
        source: 'media9.ro',
        author: 'Echipa Călin Cozma',
        create_at: '10 Mai 2024',
    },
    {
        id: '5',
        title: 'Călin Cozma: Combaterea minciunii și amăgirii în administrația locală',
        slug:'george-simion-calin-cozma-combaterea-minciunii-si-amagirii-in-administratia-locala',
        screens: blogImg5,
        description: 'Descoperă angajamentul lui Călin Cozma pentru transparență și corectitudine în administrația locală. Află cum își propune să lupte împotriva minciunii și amăgirii și să aducă schimbări pozitive în Cluj-Napoca.',
        text: 'Astăzi, în Piața Avram Iancu din Cluj-Napoca, Alianța pentru Unirea Românilor (AUR) și-a prezentat candidații pentru alegerile locale și europarlamentare din data de 9 iunie. Într-un discurs tranșant, președintele AUR, George Simion, a subliniat determinarea partidului de a lupta împotriva sistemului care a afectat România. În cadrul evenimentului, Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a evidențiat nevoia de transparență și onestitate în administrația locală, pledând pentru o schimbare profundă în relația dintre autorități și cetățeni.',
        quote:'Cred ca trebuie sa debirocratizam urgent, sa digitalizam, sa avem criterii clare pentru caietele de sarcini, in principal, sa ne dorim sa facem proiecte!',
        text2: 'Într-un interviu pentru presa locală, Călin Cozma a exprimat frustrarea clujenilor față de promisiunile neîndeplinite și birocratizarea excesivă din ultimii ani. El propune debirocratizarea urgentă a primăriei, digitalizarea proceselor și o colaborare bazată pe interesul comun, nu pe criterii politice. Cu un model de dezvoltare inspirat de orașe europene precum Viena și cu un apel la mobilizare pentru alegerile din 9 iunie, Călin Cozma își îndeamnă concetățenii să iasă la vot și să pună punct dictaturii PSD-PNL din ultimele decenii.',
        sourceLink: 'https://www.presalocala.com/2024/05/09/calin-cozma-clujenii-nu-trebuie-sa-mai-fie-amagiti-si-mintiti-de-catre-administratie/',
        source: 'media9.ro',
        author: 'Echipa Călin Cozma',
        create_at: '12 Mai 2024',
    },
    {
        id: '6',
        title: 'Călin Cozma: O Nouă Viziune pentru Cluj-Napoca',
        slug: 'Calin-Cozma-O-Noua-Viziune-pentru-Cluj-Napoca',
        screens: blogImg6,
        description: 'Află de ce Călin Cozma este candidatul dedicat schimbării în Cluj-Napoca și cum își propune să transforme orașul pentru toți locuitorii săi.',
        text: 'Călin Cozma, unul dintre candidații la primăria Clujului, promovează o viziune inclusivă pentru oraș, punând accent pe accesibilitate și egalitate. Află mai multe despre cum Cozma se angajează să asigure ca fiecare clujean să aibă oportunitatea de a trăi și prospera în oraș, indiferent de statutul economic.',
        quote: 'Doresc ca Cluj-Napoca să fie un oraș pentru toți, nu doar pentru cei bogați. Este timpul pentru o schimbare radicală care să beneficieze fiecare cetățean.',
        text2: 'În contextul unei campanii electorale vibrante, Cozma a criticat actuala administrație pentru eșecurile ei în gestionarea orașului și a promis reforme semnificative. El vizează îmbunătățirea infrastructurii urbane, accesul la locuințe accesibile și promovarea unui mediu de afaceri prosper pentru toți antreprenorii.',
        sourceLink: 'https://www.bzc.ro/aur-da-la-cluj-startul-campaniei-electorale-claudiu-tarziu-se-tem-de-noi-calin-cozma-dorim-ca-fiecare-clujean-sa-poata-trai-la-cluj-nu-doar-cei-bogati/',
        source: 'BZC.ro',
        author: 'Echipa Călin Cozma',
        create_at: '13 Mai 2024',
    },
    {
        id: '7',
        title: 'Călin Cozma: Reducerea Numărului de Angajați din Primăria Cluj-Napoca',
        slug: 'Calin-Cozma-Reducerea-Numarului-de-Angajati-din-Primaria-Cluj-Napoca',
        screens: blogImg7,
        description: 'Descoperă planurile lui Călin Cozma pentru eficientizarea administrației locale prin reducerea numărului de angajați din Primăria Cluj-Napoca.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, și-a anunțat intenția de a reduce numărul de angajați din Primărie pentru a spori eficiența și a reduce birocrația. Acest plan face parte dintr-o viziune mai amplă de restructurare și modernizare a administrației locale, menită să servească mai bine nevoile clujenilor.',
        quote: 'Adică în loc de 400 de milioane de euro să cheltuim doar 200 de milioane de euro. Vă spun ce vom face cu 200 de milioane de euro: vreo 12.000 de parcări. Nu voi da afară oameni Voi dezvolta alte departamente public-privat. În momentul acesta avem prea mulți angajați în Primăria Cluj-Napoca și avem prea multe clădiri goale pentru care se plătește apă și utilități, dar intră în paragină.',
        text2: 'Calin Cozma a subliniat că o primărie cu mai puțini angajați, dar mai bine pregătiți și motivați, va putea să ofere servicii publice de calitate superioară. El a criticat actuala administrație pentru lipsa de eficiență și a promis să implementeze reforme structurale care să optimizeze funcționarea primăriei și să reducă cheltuielile administrative inutile.',
        sourceLink: 'https://ziarulfaclia.ro/calin-cozma-vrea-sa-reduca-numarul-de-angajati-din-primaria-cluj-napoca/',
        source: 'Ziarul Făclia',
        author: 'Echipa Călin Cozma',
        create_at: '15 Mai 2024',
    },
    {
        id: '8',
        title: 'Călin Cozma: Opinii ale unui Influencer Politic Ardelean',
        slug: 'Calin-Cozma-Opinii-ale-unui-Influencer-Politic-Ardelean',
        screens: blogImg8,
        description: 'Află ce spune un influencer politic ardelean despre Călin Cozma, candidatul susținut de George Simion la Primăria Cluj-Napoca.',
        text: 'Într-un recent articol, un influencer politic ardelean și-a exprimat opinia despre Călin Cozma, candidatul susținut de George Simion pentru Primăria Cluj-Napoca. Acesta a evidențiat calitățile și determinarea lui Cozma în a aduce schimbări semnificative în administrația locală și în a susține interesele cetățenilor clujeni.',
        quote: 'Călin Cozma este văzut ca un lider puternic și dedicat, capabil să aducă o nouă direcție pentru Cluj-Napoca, cu sprijinul neclintit al lui George Simion și al partidului AUR.',
        text2: 'Articolul subliniază încrederea pe care o are influencerul politic în capacitatea lui Cozma de a implementa reforme esențiale și de a transforma Cluj-Napoca într-un oraș mai bine administrat și mai prosper. Cu o viziune clară și o echipă puternică în spate, Călin Cozma se angajează să lupte pentru binele comunității și să ofere soluții concrete pentru problemele locale.',
        sourceLink: 'https://apuseni.info/2024/05/19/ce-spune-un-influencer-politic-ardelean-despre-omul-lui-george-simion-de-la-cluj/',
        source: 'Apuseni.info',
        author: 'Echipa Călin Cozma',
        create_at: '19 Mai 2024',
    },
    {
        id: '9',
        title: 'Călin Cozma: Amintiri din Timpul Revoluției',
        slug: 'Calin-Cozma-Amintiri-din-Timpul-Revolutiei',
        screens: blogImg9,
        description: 'Descoperă povestea emoționantă a lui Călin Cozma despre curajul mamei sale în timpul Revoluției și impactul acestor evenimente asupra viziunii sale politice.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a împărtășit recent o poveste emoționantă despre curajul mamei sale în timpul Revoluției din 1989. Mama lui Cozma lucra la fabrica Continental și, în timpul evenimentelor revoluționare, a fost nevoită să fugă pe jos până în Mănăștur. Această experiență a avut un impact profund asupra lui Cozma, influențându-i angajamentul de a lupta pentru dreptate și adevăr în comunitatea sa.',
        quote: 'În timpul Revoluţiei mama lucra la Continental şi a ieşit de acolo printre morţi şi a fugit pe jos până în Mănăştur',
        text2: 'Călin Cozma a subliniat că aceste amintiri din copilărie l-au motivat să se implice activ în politică și să lupte pentru o administrație transparentă și corectă. El crede că experiențele dificile prin care a trecut familia sa i-au oferit o perspectivă unică asupra nevoilor și aspirațiilor clujenilor. În campania sa electorală, Cozma promite să aducă schimbări pozitive și să protejeze valorile pentru care au luptat mulți români în trecut.',
        sourceLink: 'https://gazetadecluj.ro/calin-cozma-in-timpul-revolutiei-mama-lucra-la-continental-si-a-iesit-de-acolo-printre-morti-si-a-fugit-pe-jos-pana-in-manastur/#google_vignette',
        source: 'Gazeta de Cluj',
        author: 'Echipa Călin Cozma',
        create_at: '20 Mai 2024',
    },
    {
        id: '10',
        title: 'Călin Cozma: Critici la Adresa Administrației Boc pentru Întârzierile în Emiterea Autorizațiilor de Construcție',
        slug: 'Calin-Cozma-Critici-la-Adresa-Administratiei-Boc-pentru-Intarzierile-in-Emiterea-Autorizatiilor-de-Constructie',
        screens: blogImg10,
        description: 'Călin Cozma critică administrația Boc pentru întârzierile în emiterea autorizațiilor de construcție și impactul acestora asupra prețurilor chiriilor în Cluj-Napoca.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a adus critici dure administrației actuale conduse de Emil Boc, acuzând întârzieri semnificative în emiterea autorizațiilor de construcție. Cozma a subliniat că domnul Boc are nevoie de trei sau patru ani pentru a emite o autorizație, ceea ce contribuie la creșterea prețurilor chiriilor în oraș din cauza cererii mari și ofertei insuficiente.',
        quote: 'În momentul în care cererea este mare și oferta este foarte mică, prețurile chiriilor cresc. Trebuie să simplificăm și să accelerăm procesul de emitere a autorizațiilor pentru a răspunde nevoilor clujenilor.',
        text2: 'Cozma a subliniat necesitatea urgentă de a debirocratiza și eficientiza procedurile administrative pentru a stimula dezvoltarea urbană și a reduce presiunea asupra pieței imobiliare. El promite să implementeze reforme care să reducă timpul de așteptare pentru autorizațiile de construcție și să facă administrația locală mai responsabilă și mai receptivă la nevoile cetățenilor.',
        sourceLink: 'https://www.news.ro/politic-intern/candidatul-aur-primaria-cluj-napoca-domnul-boc-nevoie-trei-ani-patru-ani-emita-autorizatie-constructie-momentul-cererea-mare-oferta-foarte-simplu-aceste-preturi-chirii-cresc-1922401621362024052321599998',
        source: 'News.ro',
        author: 'Echipa Călin Cozma',
        create_at: '21 Mai 2024',
    },
    {
        id: '11',
        title: 'Călin Cozma: Propuneri pentru Modernizarea Administrației în Cluj-Napoca',
        slug: 'Calin-Cozma-Propuneri-pentru-Modernizarea-Administratiei-in-Cluj-Napoca',
        screens: blogImg11,
        description: 'Află despre propunerile lui Călin Cozma pentru mutarea părții birocratice în periferia orașului și eficientizarea transportului public în Cluj-Napoca.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a propus două măsuri simple și eficiente pentru modernizarea administrației locale: mutarea părții birocratice în periferia orașului și transformarea transportului public într-un sistem eficient și accesibil. Aceste propuneri au fost prezentate ca soluții pentru decongestionarea centrului orașului și pentru îmbunătățirea calității vieții clujenilor.',
        quote: 'Mutarea părții birocratice la periferie va elibera centrul Clujului și va face loc pentru spații publice și zone verzi. În plus, un transport public eficient va reduce traficul și va face orașul mai accesibil pentru toți cetățenii.',
        text2: 'Cozma a explicat că un Palat Administrativ situat la periferia orașului ar reduce considerabil aglomerația din centrul Clujului, permițând astfel dezvoltarea urbană și crearea unor noi spații pentru locuitori. De asemenea, propune ca transportul comun să fie gratuit pentru a încuraja utilizarea acestuia și pentru a reduce poluarea și congestia rutieră. Aceste măsuri, spune el, sunt esențiale pentru a transforma Cluj-Napoca într-un oraș modern și sustenabil.',
        sourceLink: 'https://www.news.ro/politic-intern/candidatul-aur-primaria-cluj-napoca-propus-doua-lucruri-foarte-simple-palat-administrativ-periferia-orasului-mutam-toata-partea-birocratica-centrul-clujului-anaf-ul-transportul-comun-ar-trebui-fie-1922403321032024052221599918',
        source: 'News.ro',
        author: 'Echipa Călin Cozma',
        create_at: '23 Mai 2024',
    },
    {
        id: '12',
        title: 'AUR Denunță Acțiuni de Intimidare și Vandalizare în Campania din Cluj',
        slug: 'Calin-Cozma-AUR-Denunta-Actiuni-de-Intimidare-si-Vandalizare-in-Campania-din-Cluj',
        screens: blogImg12,
        description: 'Află despre acțiunile de intimidare și vandalizare raportate de AUR în timpul campaniei electorale din Cluj-Napoca și răspunsul partidului la aceste incidente.',
        text: 'Alianța pentru Unirea Românilor (AUR) a raportat recent acțiuni de intimidare și vandalizare în timpul campaniei electorale din Cluj-Napoca. Potrivit reprezentanților partidului, afișele electorale au fost distruse, iar echipele de campanie au fost supuse unor presiuni constante. AUR condamnă ferm aceste acțiuni și solicită autorităților să ia măsuri pentru a asigura desfășurarea corectă și transparentă a procesului electoral.',
        quote: 'Votați patrioți români. Dați-ne o șansă',
        text2: 'Partidul AUR își exprimă determinarea de a continua campania electorală, în ciuda obstacolelor întâmpinate, și îndeamnă cetățenii să iasă la vot pe 9 iunie pentru a aduce schimbarea de care Cluj-Napoca are nevoie. Reprezentanții partidului subliniază importanța unei campanii desfășurate în mod civilizat și legal, unde fiecare candidat are dreptul să își prezinte programul fără teama de represalii.',
        sourceLink: 'https://ziarulfaclia.ro/aur-denunta-actiuni-de-intimidare-si-vandalizare-in-campania-din-cluj/',
        source: 'Ziarul Făclia',
        author: 'Echipa Călin Cozma',
        create_at: '24 Mai 2024',
    }
    
    

];
export default blogs;