// images
import blogImg1 from "/public/images/blog/primaria-cluj-napoca-calin-cozma-aur.webp";
import blogImg2 from "/public/images/blog/transparenta-si-onestitate-viziunea-lui-Calin-Cozma-pentru-administratia-locala-din-cluj-napoca.webp";
import blogImg3 from "/public/images/blog/Calin-Cozma-Sustinerea-mediului-antreprenorial-prin-festivaluri-si-expozitii.webp";
import blogImg4 from "/public/images/blog/Calin-Cozma-Reactii-la-rezultatele-sondajului-pentru-Primaria-Clujului.webp";
import blogImg5 from "/public/images/blog/george-simion-calin-cozma-combaterea-minciunii-si-amagirii-in-administratia-locala.webp";
import blogImg6 from "/public/images/blog/Calin-Cozma-O-Noua-Viziune-pentru-Cluj-Napoca.webp";
import blogImg7 from "/public/images/blog/Calin-Cozma-Reducerea-Numarului-de-Angajati-din-Primaria-Cluj-Napoca.webp";
import blogImg8 from "/public/images/blog/Calin-Cozma-Opinii-ale-unui-Influencer-Politic-Ardelean.webp";
import blogImg9 from "/public/images/blog/Calin-Cozma-Amintiri-din-Timpul-Revolutiei.webp";
import blogImg10 from "/public/images/blog/Calin-Cozma-Critici-la-Adresa-Administratiei-Boc-pentru-Intarzierile-in-Emiterea-Autorizatiilor-de-Constructie.webp";
import blogImg11 from "/public/images/blog/Calin-Cozma-Propuneri-pentru-Modernizarea-Administratiei-in-Cluj-Napoca.webp";
import blogImg12 from "/public/images/blog/Calin-Cozma-AUR-Denunta-Actiuni-de-Intimidare-si-Vandalizare-in-Campania-din-Cluj.webp";
import blogImg13 from "/public/images/blog/Candidatul-Aur-Calin-Cozma-A-Fost-Interzis-Pentru-A-Mai-Candida-Online-Doua-Mandate.webp";
import blogImg14 from "/public/images/blog/Calin-Cozma-Ateneul-Copiilor-Turism-Cluj-Napoca.webp";
import blogImg15 from "/public/images/blog/Calin-Cozma-Prioritate-Parcari-Pasaje-Subterane.webp";
import blogImg16 from "/public/images/blog/Calin-Cozma-Solutii-Autorizații-Constructie-Cluj-Napoca.webp";
import blogImg17 from "/public/images/blog/Calin-Cozma-Alegerea-Intre-Metrou-Centura-Metropolitana-Cluj-Napoca.webp";


const blogs = [
    {
        id: '1',
        title: 'Călin Cozma: Candidatura la Primăria Clujului',
        slug:'Calin-Cozma-Candidatura-la-Primaria-Clujului',
        screens: blogImg1,
        description: 'Descoperă motivele pentru care Călin Cozma și-a anunțat candidatura la Primăria Clujului în alegerile din 2024 și viziunea sa pentru oraș.',
        text: 'Călin Cozma este candidatul care își propune să aducă schimbarea în Cluj-Napoca. Artist liric de renume și antreprenor cu experiență, Călin Cozma și-a asumat această candidatură pentru a contribui la dezvoltarea orașului nostru. În articolul de mai jos, vei afla mai multe despre motivele care l-au determinat pe Călin Cozma să intre în cursa pentru Primăria Clujului și despre viziunea sa pentru viitorul orașului.',
        quote:'Sunt singurul dintre candidații înscriși în competiție născut în Cluj-Napoca. Un clujean, român și patriot care își dorește să dezvolte confortul și bunăstarea fiecărui cetățean al acestei urbe! Nu mă lupt pentru o funcție, mă lupt pentru viitorul familiei mele, pentru viitorul Clujului!',
        text2: 'Candidatul pentru Consiliul Local își asumă un angajament hotărât: să formeze o majoritate solidă alături de colegii săi consilieri și să ofere Clujului un nou primar. Este timpul ca orașul să beneficieze de un nou început, iar acesta pare să fie sentimentul general. O nouă conducere poate aduce schimbarea necesară și așteptată de comunitate. Învierea spiritului civic și a responsabilității este esențială pentru viitorul orașului. Se pare că acesta este momentul potrivit pentru o transformare. Cu o experiență variată, de la domeniul artistic la cel antreprenorial, candidatul aduce în competiție o perspectivă proaspătă și o viziune clară asupra direcției în care ar trebui să se îndrepte Cluj-Napoca. Este evident că orașul are nevoie de o schimbare și este datoria noastră să ne asigurăm că viitorul său este mai luminos.',
        sourceLink: 'https://cluj24.ro/aur-si-a-desemnat-candidatul-la-primaria-cluj-calin-cozma-sunt-singurul-dintre-candidatii-inscrisi-nascut-in-cluj-napoca-205650.html',
        source: 'Cluj24.ro',
        author: 'Echipa Călin Cozma',
        create_at: '3 Mai 2024',
    },
    {
        id: '2',
        title: 'Transparență și Onestitate: Viziunea lui Călin Cozma pentru Administrația Locală din Cluj-Napoca',
        slug:'transparenta-si-onestitate-viziunea-lui-Calin-Cozma-pentru-administratia-locala-din-cluj-napoca',
        screens: blogImg2,
        description: 'Călin Cozma subliniază importanța transparenței și onestității în administrația locală și îndeamnă clujenii să nu mai fie amăgiți și mințiți de către administrație.',
        text: 'Călin Cozma este un adept fervent al transparenței și onestității în administrația locală. Într-un interviu recent, el a subliniat importanța comunicării deschise și corecte între autorități și cetățeni. Îndeamnă clujenii să fie vigilenți și să ceară explicații clare și detaliate cu privire la deciziile și acțiunile administrației. Este timpul ca locuitorii Clujului să aibă acces la informații corecte și complete despre modul în care este condus orașul lor.',
        quote:'„Urbea are nevoie de  festivaluri, târguri şi expoziţii  de care să beneficieze tot mediul antreprenorial, nu doar firmele din ţarcul UNTOLD”',
        text2: 'Candidatul pentru Consiliul Local își asumă un angajament hotărât: să formeze o majoritate solidă alături de colegii săi consilieri și să ofere Clujului un nou primar. Este timpul ca orașul să beneficieze de un nou început, iar acesta pare să fie sentimentul general. O nouă conducere poate aduce schimbarea necesară și așteptată de comunitate. Învierea spiritului civic și a responsabilității este esențială pentru viitorul orașului. Se pare că acesta este momentul potrivit pentru o transformare. Cu o experiență variată, de la domeniul artistic la cel antreprenorial, candidatul aduce în competiție o perspectivă proaspătă și o viziune clară asupra direcției în care ar trebui să se îndrepte Cluj-Napoca. Este evident că orașul are nevoie de o schimbare și este datoria noastră să ne asigurăm că viitorul său este mai luminos.',
        sourceLink: 'https://www.presalocala.com/2024/05/09/calin-cozma-clujenii-nu-trebuie-sa-mai-fie-amagiti-si-mintiti-de-catre-administratie/',
        source: 'presalocala.com',
        author: 'Echipa Călin Cozma',
        create_at: '5 Mai 2024',
    },
    {
        id: '3',
        title: 'Călin Cozma: Susținerea mediului antreprenorial prin festivaluri și expoziții',
        slug:'Calin-Cozma-Sustinerea-mediului-antreprenorial-prin-festivaluri-si-expozitii',
        screens: blogImg3,
        description: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, pune accentul pe susținerea mediului antreprenorial local și critică administrația condusă de Emil Boc pentru tratamentul discriminatoriu și birocrația excesivă. ',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a adus în atenția publicului un mesaj ferm cu privire la administrația locală condusă de Emil Boc. El subliniază necesitatea ca întregul mediu antreprenorial din Cluj să beneficieze de evenimente precum festivaluri, târguri și expoziții, nu doar câteva firme privilegiate. Cozma evidențiază dificultățile cu care se confruntă micii întreprinzători, precum chiriile exorbitante, birocrația excesivă și preferințele acordate anumitor operatori economici. Propunerile sale includ simplificarea procedurilor administrative și promovarea unei relații civilizate între administrație și antreprenori, în conformitate cu legea.',
        quote:'Urbea are nevoie de  festivaluri, târguri şi expoziţii  de care să beneficieze tot mediul antreprenorial, nu doar firmele din ţarcul UNTOLD',
        text2: 'În continuare, candidatul AUR la Primăria Cluj-Napoca, Călin Cozma, subliniază că prioritățile sale se axează pe sprijinirea tuturor afacerilor locale și crearea unui mediu propice dezvoltării acestora. El propune soluții rapide și eficiente pentru problemele întâmpinate de antreprenori, iar angajamentul său pentru o administrație transparentă și echitabilă este clar evidențiat. Cozma promite să acorde atenție tuturor sectoarelor economice și să lupte pentru ca niciun business să nu fie tratat discriminatoriu, pledând pentru o abordare justă și deschisă în toate relațiile cu mediul antreprenorial din Cluj-Napoca.',
        sourceLink: 'https://gazetadecluj.ro/calin-cozma-urbea-are-nevoie-de-festivaluri-targuri-si-expozitii-de-care-sa-beneficieze-tot-mediul-antreprenorial-nu-doar-firmele-din-tarcul-untold/',
        source: 'gazetadecluj.ro',
        author: 'Echipa Călin Cozma',
        create_at: '7 Mai 2024',
    },
    {
        id: '4',
        title: 'Călin Cozma: Reacții la rezultatele sondajului pentru Primăria Clujului',
        slug:'Calin-Cozma-Reactii-la-rezultatele-sondajului-pentru-Primaria-Clujului',
        screens: blogImg4,
        description: 'Călin Cozma subliniază rolul crucial al organizării festivalurilor, târgurilor și expozițiilor în susținerea și dezvoltarea mediului antreprenorial din Cluj-Napoca. Prin aceste evenimente, el își propune să ofere oportunități semnificative de promovare și dezvoltare pentru afacerile locale.',
        text: 'În urma publicării rezultatelor unui sondaj de opinie privind alegerile pentru Primăria Clujului, Călin Cozma a exprimat satisfacția sa față de sprijinul și încrederea acordate de către cetățeni. El consideră că rezultatele sondajului reflectă dorința clujenilor de a vedea o schimbare în conducerea orașului și își exprimă hotărârea de a le oferi un nou primar și o nouă viziune pentru viitorul Clujului.',
        quote:'Clujenii nu trebuie să mai fie amăgiți și mințiți de către administrație!',
        text2: 'Candidatul pentru Consiliul Local își asumă un angajament hotărât: să formeze o majoritate solidă alături de colegii săi consilieri și să ofere Clujului un nou primar. Este timpul ca orașul să beneficieze de un nou început, iar acesta pare să fie sentimentul general. O nouă conducere poate aduce schimbarea necesară și așteptată de comunitate. Învierea spiritului civic și a responsabilității este esențială pentru viitorul orașului. Se pare că acesta este momentul potrivit pentru o transformare. Cu o experiență variată, de la domeniul artistic la cel antreprenorial, candidatul aduce în competiție o perspectivă proaspătă și o viziune clară asupra direcției în care ar trebui să se îndrepte Cluj-Napoca. Este evident că orașul are nevoie de o schimbare și este datoria noastră să ne asigurăm că viitorul său este mai luminos.',
        sourceLink: 'https://www.presalocala.com/2024/05/09/calin-cozma-clujenii-nu-trebuie-sa-mai-fie-amagiti-si-mintiti-de-catre-administratie/',
        source: 'media9.ro',
        author: 'Echipa Călin Cozma',
        create_at: '10 Mai 2024',
    },
    {
        id: '5',
        title: 'Călin Cozma: Combaterea minciunii și amăgirii în administrația locală',
        slug:'george-simion-calin-cozma-combaterea-minciunii-si-amagirii-in-administratia-locala',
        screens: blogImg5,
        description: 'Descoperă angajamentul lui Călin Cozma pentru transparență și corectitudine în administrația locală. Află cum își propune să lupte împotriva minciunii și amăgirii și să aducă schimbări pozitive în Cluj-Napoca.',
        text: 'Astăzi, în Piața Avram Iancu din Cluj-Napoca, Alianța pentru Unirea Românilor (AUR) și-a prezentat candidații pentru alegerile locale și europarlamentare din data de 9 iunie. Într-un discurs tranșant, președintele AUR, George Simion, a subliniat determinarea partidului de a lupta împotriva sistemului care a afectat România. În cadrul evenimentului, Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a evidențiat nevoia de transparență și onestitate în administrația locală, pledând pentru o schimbare profundă în relația dintre autorități și cetățeni.',
        quote:'Cred ca trebuie sa debirocratizam urgent, sa digitalizam, sa avem criterii clare pentru caietele de sarcini, in principal, sa ne dorim sa facem proiecte!',
        text2: 'Într-un interviu pentru presa locală, Călin Cozma a exprimat frustrarea clujenilor față de promisiunile neîndeplinite și birocratizarea excesivă din ultimii ani. El propune debirocratizarea urgentă a primăriei, digitalizarea proceselor și o colaborare bazată pe interesul comun, nu pe criterii politice. Cu un model de dezvoltare inspirat de orașe europene precum Viena și cu un apel la mobilizare pentru alegerile din 9 iunie, Călin Cozma își îndeamnă concetățenii să iasă la vot și să pună punct dictaturii PSD-PNL din ultimele decenii.',
        sourceLink: 'https://www.presalocala.com/2024/05/09/calin-cozma-clujenii-nu-trebuie-sa-mai-fie-amagiti-si-mintiti-de-catre-administratie/',
        source: 'media9.ro',
        author: 'Echipa Călin Cozma',
        create_at: '12 Mai 2024',
    },
    {
        id: '6',
        title: 'Călin Cozma: O Nouă Viziune pentru Cluj-Napoca',
        slug: 'Calin-Cozma-O-Noua-Viziune-pentru-Cluj-Napoca',
        screens: blogImg6,
        description: 'Află de ce Călin Cozma este candidatul dedicat schimbării în Cluj-Napoca și cum își propune să transforme orașul pentru toți locuitorii săi.',
        text: 'Călin Cozma, unul dintre candidații la primăria Clujului, promovează o viziune inclusivă pentru oraș, punând accent pe accesibilitate și egalitate. Află mai multe despre cum Cozma se angajează să asigure ca fiecare clujean să aibă oportunitatea de a trăi și prospera în oraș, indiferent de statutul economic.',
        quote: 'Doresc ca Cluj-Napoca să fie un oraș pentru toți, nu doar pentru cei bogați. Este timpul pentru o schimbare radicală care să beneficieze fiecare cetățean.',
        text2: 'În contextul unei campanii electorale vibrante, Cozma a criticat actuala administrație pentru eșecurile ei în gestionarea orașului și a promis reforme semnificative. El vizează îmbunătățirea infrastructurii urbane, accesul la locuințe accesibile și promovarea unui mediu de afaceri prosper pentru toți antreprenorii.',
        sourceLink: 'https://www.bzc.ro/aur-da-la-cluj-startul-campaniei-electorale-claudiu-tarziu-se-tem-de-noi-calin-cozma-dorim-ca-fiecare-clujean-sa-poata-trai-la-cluj-nu-doar-cei-bogati/',
        source: 'BZC.ro',
        author: 'Echipa Călin Cozma',
        create_at: '13 Mai 2024',
    },
    {
        id: '7',
        title: 'Călin Cozma: Reducerea Numărului de Angajați din Primăria Cluj-Napoca',
        slug: 'Calin-Cozma-Reducerea-Numarului-de-Angajati-din-Primaria-Cluj-Napoca',
        screens: blogImg7,
        description: 'Descoperă planurile lui Călin Cozma pentru eficientizarea administrației locale prin reducerea numărului de angajați din Primăria Cluj-Napoca.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, și-a anunțat intenția de a reduce numărul de angajați din Primărie pentru a spori eficiența și a reduce birocrația. Acest plan face parte dintr-o viziune mai amplă de restructurare și modernizare a administrației locale, menită să servească mai bine nevoile clujenilor.',
        quote: 'Adică în loc de 400 de milioane de euro să cheltuim doar 200 de milioane de euro. Vă spun ce vom face cu 200 de milioane de euro: vreo 12.000 de parcări. Nu voi da afară oameni Voi dezvolta alte departamente public-privat. În momentul acesta avem prea mulți angajați în Primăria Cluj-Napoca și avem prea multe clădiri goale pentru care se plătește apă și utilități, dar intră în paragină.',
        text2: 'Calin Cozma a subliniat că o primărie cu mai puțini angajați, dar mai bine pregătiți și motivați, va putea să ofere servicii publice de calitate superioară. El a criticat actuala administrație pentru lipsa de eficiență și a promis să implementeze reforme structurale care să optimizeze funcționarea primăriei și să reducă cheltuielile administrative inutile.',
        sourceLink: 'https://ziarulfaclia.ro/calin-cozma-vrea-sa-reduca-numarul-de-angajati-din-primaria-cluj-napoca/',
        source: 'Ziarul Făclia',
        author: 'Echipa Călin Cozma',
        create_at: '15 Mai 2024',
    },
    {
        id: '8',
        title: 'Călin Cozma: Opinii ale unui Influencer Politic Ardelean',
        slug: 'Calin-Cozma-Opinii-ale-unui-Influencer-Politic-Ardelean',
        screens: blogImg8,
        description: 'Află ce spune un influencer politic ardelean despre Călin Cozma, candidatul susținut de George Simion la Primăria Cluj-Napoca.',
        text: 'Într-un recent articol, un influencer politic ardelean și-a exprimat opinia despre Călin Cozma, candidatul susținut de George Simion pentru Primăria Cluj-Napoca. Acesta a evidențiat calitățile și determinarea lui Cozma în a aduce schimbări semnificative în administrația locală și în a susține interesele cetățenilor clujeni.',
        quote: 'Călin Cozma este văzut ca un lider puternic și dedicat, capabil să aducă o nouă direcție pentru Cluj-Napoca, cu sprijinul neclintit al lui George Simion și al partidului AUR.',
        text2: 'Articolul subliniază încrederea pe care o are influencerul politic în capacitatea lui Cozma de a implementa reforme esențiale și de a transforma Cluj-Napoca într-un oraș mai bine administrat și mai prosper. Cu o viziune clară și o echipă puternică în spate, Călin Cozma se angajează să lupte pentru binele comunității și să ofere soluții concrete pentru problemele locale.',
        sourceLink: 'https://apuseni.info/2024/05/19/ce-spune-un-influencer-politic-ardelean-despre-omul-lui-george-simion-de-la-cluj/',
        source: 'Apuseni.info',
        author: 'Echipa Călin Cozma',
        create_at: '19 Mai 2024',
    },
    {
        id: '9',
        title: 'Călin Cozma: Amintiri din Timpul Revoluției',
        slug: 'Calin-Cozma-Amintiri-din-Timpul-Revolutiei',
        screens: blogImg9,
        description: 'Descoperă povestea emoționantă a lui Călin Cozma despre curajul mamei sale în timpul Revoluției și impactul acestor evenimente asupra viziunii sale politice.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a împărtășit recent o poveste emoționantă despre curajul mamei sale în timpul Revoluției din 1989. Mama lui Cozma lucra la fabrica Continental și, în timpul evenimentelor revoluționare, a fost nevoită să fugă pe jos până în Mănăștur. Această experiență a avut un impact profund asupra lui Cozma, influențându-i angajamentul de a lupta pentru dreptate și adevăr în comunitatea sa.',
        quote: 'În timpul Revoluţiei mama lucra la Continental şi a ieşit de acolo printre morţi şi a fugit pe jos până în Mănăştur',
        text2: 'Călin Cozma a subliniat că aceste amintiri din copilărie l-au motivat să se implice activ în politică și să lupte pentru o administrație transparentă și corectă. El crede că experiențele dificile prin care a trecut familia sa i-au oferit o perspectivă unică asupra nevoilor și aspirațiilor clujenilor. În campania sa electorală, Cozma promite să aducă schimbări pozitive și să protejeze valorile pentru care au luptat mulți români în trecut.',
        sourceLink: 'https://gazetadecluj.ro/calin-cozma-in-timpul-revolutiei-mama-lucra-la-continental-si-a-iesit-de-acolo-printre-morti-si-a-fugit-pe-jos-pana-in-manastur/#google_vignette',
        source: 'Gazeta de Cluj',
        author: 'Echipa Călin Cozma',
        create_at: '20 Mai 2024',
    },
    {
        id: '10',
        title: 'Călin Cozma: Critici la Adresa Administrației Boc pentru Întârzierile în Emiterea Autorizațiilor de Construcție',
        slug: 'Calin-Cozma-Critici-la-Adresa-Administratiei-Boc-pentru-Intarzierile-in-Emiterea-Autorizatiilor-de-Constructie',
        screens: blogImg10,
        description: 'Călin Cozma critică administrația Boc pentru întârzierile în emiterea autorizațiilor de construcție și impactul acestora asupra prețurilor chiriilor în Cluj-Napoca.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a adus critici dure administrației actuale conduse de Emil Boc, acuzând întârzieri semnificative în emiterea autorizațiilor de construcție. Cozma a subliniat că domnul Boc are nevoie de trei sau patru ani pentru a emite o autorizație, ceea ce contribuie la creșterea prețurilor chiriilor în oraș din cauza cererii mari și ofertei insuficiente.',
        quote: 'În momentul în care cererea este mare și oferta este foarte mică, prețurile chiriilor cresc. Trebuie să simplificăm și să accelerăm procesul de emitere a autorizațiilor pentru a răspunde nevoilor clujenilor.',
        text2: 'Cozma a subliniat necesitatea urgentă de a debirocratiza și eficientiza procedurile administrative pentru a stimula dezvoltarea urbană și a reduce presiunea asupra pieței imobiliare. El promite să implementeze reforme care să reducă timpul de așteptare pentru autorizațiile de construcție și să facă administrația locală mai responsabilă și mai receptivă la nevoile cetățenilor.',
        sourceLink: 'https://www.news.ro/politic-intern/candidatul-aur-primaria-cluj-napoca-domnul-boc-nevoie-trei-ani-patru-ani-emita-autorizatie-constructie-momentul-cererea-mare-oferta-foarte-simplu-aceste-preturi-chirii-cresc-1922401621362024052321599998',
        source: 'News.ro',
        author: 'Echipa Călin Cozma',
        create_at: '21 Mai 2024',
    },
    {
        id: '11',
        title: 'Călin Cozma: Propuneri pentru Modernizarea Administrației în Cluj-Napoca',
        slug: 'Calin-Cozma-Propuneri-pentru-Modernizarea-Administratiei-in-Cluj-Napoca',
        screens: blogImg11,
        description: 'Află despre propunerile lui Călin Cozma pentru mutarea părții birocratice în periferia orașului și eficientizarea transportului public în Cluj-Napoca.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a propus două măsuri simple și eficiente pentru modernizarea administrației locale: mutarea părții birocratice în periferia orașului și transformarea transportului public într-un sistem eficient și accesibil. Aceste propuneri au fost prezentate ca soluții pentru decongestionarea centrului orașului și pentru îmbunătățirea calității vieții clujenilor.',
        quote: 'Mutarea părții birocratice la periferie va elibera centrul Clujului și va face loc pentru spații publice și zone verzi. În plus, un transport public eficient va reduce traficul și va face orașul mai accesibil pentru toți cetățenii.',
        text2: 'Cozma a explicat că un Palat Administrativ situat la periferia orașului ar reduce considerabil aglomerația din centrul Clujului, permițând astfel dezvoltarea urbană și crearea unor noi spații pentru locuitori. De asemenea, propune ca transportul comun să fie gratuit pentru a încuraja utilizarea acestuia și pentru a reduce poluarea și congestia rutieră. Aceste măsuri, spune el, sunt esențiale pentru a transforma Cluj-Napoca într-un oraș modern și sustenabil.',
        sourceLink: 'https://www.news.ro/politic-intern/candidatul-aur-primaria-cluj-napoca-propus-doua-lucruri-foarte-simple-palat-administrativ-periferia-orasului-mutam-toata-partea-birocratica-centrul-clujului-anaf-ul-transportul-comun-ar-trebui-fie-1922403321032024052221599918',
        source: 'News.ro',
        author: 'Echipa Călin Cozma',
        create_at: '23 Mai 2024',
    },
    {
        id: '12',
        title: 'AUR Denunță Acțiuni de Intimidare și Vandalizare în Campania din Cluj',
        slug: 'Calin-Cozma-AUR-Denunta-Actiuni-de-Intimidare-si-Vandalizare-in-Campania-din-Cluj',
        screens: blogImg12,
        description: 'Află despre acțiunile de intimidare și vandalizare raportate de AUR în timpul campaniei electorale din Cluj-Napoca și răspunsul partidului la aceste incidente.',
        text: 'Alianța pentru Unirea Românilor (AUR) a raportat recent acțiuni de intimidare și vandalizare în timpul campaniei electorale din Cluj-Napoca. Potrivit reprezentanților partidului, afișele electorale au fost distruse, iar echipele de campanie au fost supuse unor presiuni constante. AUR condamnă ferm aceste acțiuni și solicită autorităților să ia măsuri pentru a asigura desfășurarea corectă și transparentă a procesului electoral.',
        quote: 'Votați patrioți români. Dați-ne o șansă',
        text2: 'Partidul AUR își exprimă determinarea de a continua campania electorală, în ciuda obstacolelor întâmpinate, și îndeamnă cetățenii să iasă la vot pe 9 iunie pentru a aduce schimbarea de care Cluj-Napoca are nevoie. Reprezentanții partidului subliniază importanța unei campanii desfășurate în mod civilizat și legal, unde fiecare candidat are dreptul să își prezinte programul fără teama de represalii.',
        sourceLink: 'https://ziarulfaclia.ro/aur-denunta-actiuni-de-intimidare-si-vandalizare-in-campania-din-cluj/',
        source: 'Ziarul Făclia',
        author: 'Echipa Călin Cozma',
        create_at: '24 Mai 2024',
    },
    {
        id: '13',
        title: 'Călin Cozma, Candidatul AUR, Interzis pentru a Mai Candida Online pentru Încă Două Mandate',
        slug: 'Candidatul-Aur-Calin-Cozma-A-Fost-Interzis-Pentru-A-Mai-Candida-Online-Doua-Mandate',
        screens: blogImg13,
        description: 'Află despre interdicția impusă candidatului AUR, Călin Cozma, care nu va mai putea candida online pentru încă două mandate.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a primit recent o notificare de la Facebook care spune: "Your account is restricted for 3,649 days. Your account activity didn\'t follow our Community Standards, so you can\'t do one or more things you usually do." Această măsură a fost luată nu pentru că Călin Cozma ar fi încălcat standardele comunității, ci pentru că cineva a încercat să oprească libera exprimare. Conform informațiilor furnizate, Cozma nu va putea folosi platformele online pentru a-și desfășura campania electorală, ceea ce reprezintă un obstacol semnificativ în strategia sa de comunicare cu oamenii din Cluj.',
        quote: 'Această interdicție este un atac direct asupra democrației și libertății de exprimare. Este inacceptabil ca, într-o perioadă crucială pentru campania mea, să fiu privat de o platformă esențială pentru a comunica cu cetățenii.',
        text2: 'Reprezentanții AUR au declarat că vor contesta această decizie și că vor căuta toate căile legale pentru a asigura că Călin Cozma poate continua să-și desfășoare campania electorală. În ciuda acestor provocări, Cozma rămâne determinat să lupte pentru schimbare și să aducă o nouă viziune în administrația locală din Cluj-Napoca.',
        sourceLink: 'https://gazetadecluj.ro/candidatul-aur-calin-cozma-a-fost-interzis-pentru-a-mai-candida-online-inca-doua-mandate/',
        source: 'Gazeta de Cluj',
        author: 'Echipa Călin Cozma',
        create_at: '27 Mai 2024',
    },
    {
        id: '14',
        title: 'Călin Cozma Propune Crearea unui Ateneul al Copiilor și Atragerea Turismului la Cluj-Napoca',
        slug: 'Calin-Cozma-Ateneul-Copiilor-Turism-Cluj-Napoca',
        screens: blogImg14,
        description: 'Descoperă propunerile lui Călin Cozma pentru dezvoltarea infrastructurii culturale și atragerea turiștilor străini la Cluj-Napoca.',
        text: 'Invitat în emisiunea “9 întrebări în 9 minute”, produsă de Media9, Călin Cozma, candidatul AUR la Primăria Cluj-Napoca și primul pe lista pentru Consiliul Local, a discutat despre necesitatea dezvoltării infrastructurii culturale în municipiu. Cozma, un solist de operă cu experiență pe scene din România și Germania, a subliniat importanța creării unui Ateneul al Copiilor, o instituție dedicată spectacolelor și artei pentru copii. În prezent, Cluj-Napoca nu oferă suficiente oportunități culturale pentru copii cu vârste cuprinse între 8 și 18 ani, iar acest proiect ar umple acest gol crucial în dezvoltarea tinerilor.',
        quote: '“Să îți spun despre un proiect la care m-am gândit, se numește Ateneul copiilor. De ce e foarte important. Eu am copil și știu că în momentul ăsta, în Cluj-Napoca, noi nu avem instituții care să ofere spectacole pentru copii sau artă pentru copii. În București, de exemplu, sunt trei opere de copii, Opera Comică pentru Copii și încă vreo două. Până la opt ani, îl duci pe copil la Puck, la un teatru de păpuși, dar de la 8 la 18 ani nu mai ai ce să-i oferi cultură. Iar el atunci se dezvoltă ca și individ. Este foarte important pentru toți părinții care au copii să aibă unde să meargă cu copiii.”',
        text2: 'Pe lângă acest proiect, Călin Cozma a subliniat necesitatea unui centru expozițional modern și a unui proiect ambițios de promovare a istoriei Clujului. În colaborare cu istorici locali, Cozma dorește să dezvolte un program de trei zile care să prezinte povestea orașului de-a lungul a 2.000 de ani, atrăgând astfel turiști străini și promovând bogata moștenire culturală a Clujului. “Trebuie să dezvoltăm povestea Clujului... să aducem turiști la Cluj-Napoca și să aibă trei zile să vadă istoria Clujului și poveștile, pentru că există multe legende”, a adăugat Cozma.',
        sourceLink: 'https://media9.ro/solutia-pentru-atragerea-turistilor-straini-povestea-clujului-2-000-de-ani-in-trei-zile/?fbclid=IwZXh0bgNhZW0CMTAAAR0T32jsQxscJNueAAWNRFkSitl5ooEhbLAsdkhF7dpZXSRrpUK-LK2Xd8w_aem_AY0RZeVuq3JueFnPGuvLUw-opUcLxDzQhk3X3TQyJu8qy3xbPUE_cwb8AUxHQprAvmW9-Oh686gqvUyugS0-oYYC',
        source: 'Media9.ro',
        author: 'Echipa Călin Cozma',
        create_at: '29 Mai 2024',
    },
    {
        id: '15',
        title: 'Călin Cozma, Prioritate pentru Parcări și Pasaje Subterane, nu Metrou',
        slug: 'Calin-Cozma-Prioritate-Parcari-Pasaje-Subterane',
        screens: blogImg15,
        description: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, propune soluții moderne de infrastructură pentru decongestionarea traficului.',
        text: 'Călin Cozma, candidatul AUR pentru funcția de primar al Municipiului Cluj-Napoca, a afirmat în emisiunea Politik 24, moderată de jurnalistul Dinu Criste la CLUJ LIVE, că orașul are nevoie mai mare de parcări subterane în centru și de pasaje subterane și supraterane decât de o linie de metrou. Cozma a subliniat necesitatea construirii unor soluții moderne de infrastructură pentru a decongestiona traficul din centrul orașului. “Avem nevoie de mai multe parcări subterane și de pasaje subterane și supraterane pentru a rezolva problema traficului, nu de un metrou,” a declarat candidatul AUR.',
        quote: '“Avem nevoie de mai multe parcări subterane și de pasaje subterane și supraterane pentru a rezolva problema traficului, nu de un metrou.”',
        text2: 'De asemenea, Cozma a propus mutarea Festivalului Untold în afara orașului, fără a-l elimina complet. “Festivalul Untold este un eveniment important, dar ar trebui mutat în afara orașului pentru a reduce disconfortul locuitorilor,” a explicat acesta. În ceea ce privește administrația locală, Cozma a explicat necesitatea restructurării Primăriei și a firmelor controlate de aceasta, precum RADP, CTP și Termoficare. El a argumentat că numărul angajaților este prea mare și că digitalizarea instituțiilor este imperativă pentru o funcționare eficientă. Candidatul AUR a criticat și funcționarul public virtual Antonia, considerându-l ineficient. “Antonia nu este de ajutor. Tot ce poate face este să ne spună unde s-au blocat documentele în Primărie,” a spus Cozma, subliniind că este nevoie de soluții digitale mai performante. Propunerile lui Cozma vin într-un moment în care Cluj-Napoca se confruntă cu provocări majore legate de trafic și eficiența administrației publice, iar soluțiile sale au stârnit deja discuții aprinse în rândul comunității locale.',
        sourceLink: 'https://www.clujlive.ro/2024/05/30/calin-cozma-candidatul-aur-la-primaria-cluj-napoca-prioritate-pentru-parcari-si-pasaje-subterane-nu-metrou/',
        source: 'ClujLive.ro',
        author: 'Echipa Călin Cozma',
        create_at: '30 Mai 2024',
    },
    {
        id: '16',
        title: 'Călin Cozma, Candidatul AUR la Primăria Cluj-Napoca: Soluții pentru Emiterea Rapidă a Autorizațiilor de Construcție',
        slug: 'Calin-Cozma-Solutii-Autorizații-Constructie-Cluj-Napoca',
        screens: blogImg16,
        description: 'Călin Cozma propune soluții pentru emiterea rapidă a autorizațiilor de construcție în Cluj-Napoca, comparând situația actuală cu cea din alte orașe din România.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a adus în discuție problema emiterii autorizațiilor de construcție în oraș, comparând situația actuală cu eficiența observată în alte orașe din România. Această comparație reflectă frustrarea multor clujeni și subliniază nevoia urgentă de reformă în procesul de emitere a autorizațiilor.',
        quote: '“De ce la Bolojan se poate să iasă autorizație de construire în 15 zile sau în 30 de zile și la Cluj-Napoca durează trei ani?”',
        text2: 'Cozma propune soluții pentru a reduce birocrația și a accelera procesul de aprobare a proiectelor de construcție. El susține digitalizarea completă a proceselor administrative și implementarea unor termene clare și stricte pentru emiterea autorizațiilor. "Este timpul să aducem eficiență și transparență în administrația locală. Trebuie să ne asigurăm că dezvoltarea urbană nu este blocată de întârzieri inutile," a declarat Cozma. Propunerile sale vin într-un moment în care Cluj-Napoca se confruntă cu provocări majore în ceea ce privește dezvoltarea urbană și infrastructura, iar soluțiile sale au stârnit deja discuții aprinse în rândul comunității locale.',
        sourceLink: 'https://www.news.ro/politic-intern/candidatul-aur-la-primaria-cluj-napoca-de-ce-la-bolojan-se-poate-sa-iasa-autorizatie-de-construire-in-15-zile-sau-in-30-de-zile-si-la-cluj-napoca-dureaza-trei-ani-1922404803002024061721616113',
        source: 'News.ro',
        author: 'Echipa Călin Cozma',
        create_at: '3 Iunie 2024',
    },
    {
        id: '17',
        title: 'Călin Cozma: Alegerea Între Metrou și Centura Metropolitană la Cluj-Napoca',
        slug: 'Calin-Cozma-Alegerea-Intre-Metrou-Centura-Metropolitana-Cluj-Napoca',
        screens: blogImg17,
        description: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, discută despre necesitatea prioritizării proiectelor de infrastructură și alegerea între metrou și centura metropolitană.',
        text: 'Călin Cozma, candidatul AUR pentru funcția de primar al Municipiului Cluj-Napoca, a subliniat importanța prioritizării proiectelor de infrastructură pentru oraș. Într-un interviu recent, Cozma a dezvăluit că, în acest moment, există patru milioane de lei alocați pentru exproprieri în cadrul proiectului centurii metropolitane, comparativ cu cele 200 de milioane de euro necesare pentru implementarea completă a acestui proiect vital. Cozma a subliniat că orașul trebuie să facă o alegere clară între construirea unei linii de metrou și dezvoltarea centurii metropolitane, ambele fiind esențiale pentru decongestionarea traficului și îmbunătățirea mobilității urbane.',
        quote: '“În acest moment există patru milioane de lei pentru exproprieri în cadrul proiectului centurii metropolitane, comparativ cu cele 200 de milioane de euro necesare. Este crucial să alegem între metrou și centura metropolitană.”',
        text2: 'Cozma a evidențiat că fondurile actuale sunt insuficiente pentru realizarea proiectelor propuse și că este necesar un plan strategic pentru utilizarea eficientă a resurselor disponibile. El a argumentat că prioritizarea corectă a proiectelor de infrastructură poate aduce beneficii semnificative locuitorilor orașului și poate contribui la dezvoltarea sustenabilă a Clujului. “Trebuie să analizăm cu atenție necesitățile orașului și să luăm decizii informate care să reflecte realitățile financiare și nevoile urgente ale comunității,” a declarat Cozma. Propunerile sale au stârnit deja discuții aprinse în rândul comunității locale, iar alegerea între metrou și centura metropolitană rămâne un subiect de mare interes pentru toți clujenii.',
        sourceLink: 'https://www.news.ro/politic-intern/candidatul-aur-primaria-cluj-napoca-acest-moment-exista-patru-milioane-lei-exproprieri-centura-metropolitana-200-milioane-euro-cat-e-necesar-alege-intre-metrou-centura-metropolitana-1922400403002024061821616144',
        source: 'News.ro',
        author: 'Echipa Călin Cozma',
        create_at: '4 Iunie 2024',
    },
    {
        id: '18',
        title: 'Călin Cozma Critică Proiectele Nerealizate ale lui Emil Boc',
        slug: 'Calin-Cozma-Critica-Proiectele-Nerealizate-Emil-Boc',
        screens: blogImg16,
        description: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, critică dur proiectele nerealizate ale lui Emil Boc și propune soluții concrete pentru dezvoltarea orașului.',
        text: 'Călin Cozma, candidatul AUR la Primăria Cluj-Napoca, a lansat critici vehemente la adresa administrației conduse de Emil Boc, acuzând că proiectele majore, precum metroul și centura metropolitană, rămân doar promisiuni nerealizate. Cozma a evidențiat că, în ciuda numeroaselor mandate, aceste inițiative nu au fost duse la bun sfârșit, afectând negativ dezvoltarea orașului. El a subliniat necesitatea unei schimbări și a implementării unor proiecte reale care să aducă beneficii palpabile comunității.',
        quote: '“Boc a defilat cu același metrou, aceeași centură… toate proiecte vechi și nerealizate în ultimele mandate”',
        text2: 'Călin Cozma propune soluții pragmatice pentru a transforma Cluj-Napoca. El sugerează prioritizarea proiectelor de infrastructură esențiale, cum ar fi construirea de parcări subterane și supraterane, modernizarea transportului public și digitalizarea administrației locale. Cozma accentuează importanța transparenței și a eficienței în gestionarea fondurilor publice pentru a asigura un impact pozitiv asupra vieții cetățenilor. Propunerile sale vin ca răspuns la stagnarea observată sub conducerea actuală.',
        sourceLink: 'https://cluj1.ro/calin-cozma-boc-a-defilat-cu-acelasi-metrou-aceeasi-centura-toate-proiecte-vechi-si-nerealizate-in-ultimele-mandate/',
        source: 'Cluj1.ro',
        author: 'Echipa Călin Cozma',
        create_at: '10 Iulie 2024',
    }
    
    
    

];
export default blogs;